### ISSUE TITLE
Retrieve shape files (from database?)

### ISSUE THREAD

**Issue by ChloeRN** [NINAnor/NIviz#8]

**Comment by anders-kolstad** [comment]
There is some stuff here:
R:\Prosjekter\12892000_naturindeks_rammeverk_database_og_innsynslosning\Naturindeks 2020\Areal\Updated area calcs 20200607\GIS

**Comment by ChloeRN** [comment]
Øystein Solberg pointed us towards using the NI database API to extract geodata for individual indicators.
On [](https://ninweb08.nina.no/NaturindeksAPI/index.html), one navigates to "/api/Indicator/{id}/Areas" under "Indicator" and enters the indicator ID. It's then possible to download a .json file containing the spatial data. 
(This subsequently has to be converted to a shapefile for use in R).

**Comment by ChloeRN** [comment]
Øystein also noted that the necessary information for finding any indicators geodata is stored in three tables in the database:

- [Naturindeks_2012].[dbo].[Omraade]: names of indicator areas
- [Naturindeks_2012].[dbo].[Omraade_Kommune]: names of municipalities ("kommuner")/sea areas ("havområder") that lie within the indicator areas 
- [Naturindeks_2012].[dbo].[Kommune]: polygons and other geodata for municipalities/sea areas

The tables are quite large and not practical to work with as a whole. Writing an R pipeline for extracting data relevant to a specific indicator may be best in the longer term (@jenast has written similar pipelines before).

**Comment by ChloeRN** [comment]
The API can also be used for getting the larger areas for which ecosystem indices are reported. "Special" regions used in some thematic indices (e.g. alpine passerines) do not seem to be accessible through the API. @MarkusFIsraelsen will check if we have the relevant files available in the R: drive.

**Comment by ChloeRN** [comment]
Alpine passerine thematic index is presented in two large summary regions: Sør-Norge and Nord-Norge. One indicator that goes into the index, Steinskvett, has data provided at the same spatial scale. We use the shapefile for this one for the alpine passerine index here (we could not find shapefiles for the thematic index itself).
